language: csharp
mono: none
dotnet: 3.0.100
dist: bionic
git:
  depth: false
sudo: required
services:
  - docker
script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet tool install --global GitVersion.Tool --version 5.1.2
  - dotnet gitversion
  - dotnet build
  - dotnet test
cache:
  directories:
    - $HOME/.nuget